#!/usr/bin/env ruby

class Detector
  def self.detect(path)
    case File.basename(path).split('.')[-1]
    when 'js'
      :javascript
    when 'rb'
      :ruby
    end
  end
end

class Formatter
  def format(path, language)
    case language
    when :ruby
      ruby path
    when :javascript
      javascript path
    end
  end

  private

  def ruby path
    `rubocop --auto-correct --only Style spec/rails_helper.rb`
  end

  def javascript path
    `js-beautify --replace #{path}`
  end
end

dir = ARGV[0] || '*/**'

Dir[dir].each do |path|
  language = Detector.detect(path)
  unless language.nil?
    Formatter.new.format(path, language)
    puts "#{path} -> #{language}"
  end
end
