#!/usr/bin/env ruby

class Detector
  def self.detect(path)
    case File.basename(path).split('.')[-1]
    when 'js'
      :javascript
    when 'rb'
      :ruby
    end
  end
end

class Formatter
  def format(path, language)
    case language
    when :ruby
      ruby path
    when :javascript
      javascript path
    end
  end

  private

  def ruby path
    `ruby-beautify #{path}`
  end

  def javascript path
    `js-beautify --replace #{path}`
  end
end

Dir['test/*'].each do |path|
  language = Detector.detect(path)
  puts "#{path} -> #{language}"
  p Formatter.new.format(path, language)
end
